// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpyhzzog3yEOj-h7rS4lamDpO7akHSEUc',
    appId: '1:128639512320:web:2c290df7fc58e461a24de5',
    messagingSenderId: '128639512320',
    projectId: 'dalelapp-9df09',
    authDomain: 'dalelapp-9df09.firebaseapp.com',
    storageBucket: 'dalelapp-9df09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFfWJJpJ6bHO9guXWWEtM92ZbSyRdAEFk',
    appId: '1:128639512320:android:32140ed7609e8ceca24de5',
    messagingSenderId: '128639512320',
    projectId: 'dalelapp-9df09',
    storageBucket: 'dalelapp-9df09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbCXCQatGp_80yegm4wtV_AjMLYFUcPDU',
    appId: '1:128639512320:ios:31093b19f1421cbaa24de5',
    messagingSenderId: '128639512320',
    projectId: 'dalelapp-9df09',
    storageBucket: 'dalelapp-9df09.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbCXCQatGp_80yegm4wtV_AjMLYFUcPDU',
    appId: '1:128639512320:ios:31093b19f1421cbaa24de5',
    messagingSenderId: '128639512320',
    projectId: 'dalelapp-9df09',
    storageBucket: 'dalelapp-9df09.appspot.com',
    iosBundleId: 'com.example.dalelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpyhzzog3yEOj-h7rS4lamDpO7akHSEUc',
    appId: '1:128639512320:web:0337bf66540bb4bfa24de5',
    messagingSenderId: '128639512320',
    projectId: 'dalelapp-9df09',
    authDomain: 'dalelapp-9df09.firebaseapp.com',
    storageBucket: 'dalelapp-9df09.appspot.com',
  );
}
